# 前端 Dockerfile
FROM node:22-alpine AS builder

WORKDIR /app

# 复制 package.json
COPY package*.json ./7+9

RUN npm install -g pnpm --registry=https://registry.npmmirror.com

# 安装依赖
RUN pnpm install --registry=https://registry.npmmirror.com

# 复制源代码
COPY . .

# 构建
RUN npm run build

# 生产环境
FROM nginx:alpine

# 复制构建产物
COPY --from=builder /app/dist /usr/share/nginx/html

# 复制 nginx 配置
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
