spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_db?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123456
  data:
    redis:
      redisson:
        file: classpath:redisson-config.yml
  cache:
    type: redis
    redis:
      time-to-live: 300000
      cache-null-values: false

# File Upload (dev)
file:
  upload-path: /home/demo/blog-server/uploads/
