singleServerConfig:
  address: "redis://localhost:6379"
  database: 0
  connectionPoolSize: 10
  connectionMinimumIdleSize: 2
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
